function [cprops,xprops] = gd_basin_properties(grid,wl,histdst)   
%
%-------function help------------------------------------------------------
% NAME
%   gd_basin_properties.m
% PURPOSE
%   use the basin hypsometry from gd_basin_hypsometry to compute a number
%   of along-channel/x-axis morphological properties
% USAGE
%   hyps = gd_basin_properties(grid,wl,histdst)
% INPUTS
%   grid - struct of x,y,z values that define grid 
%   wl - struct of zhw, zmt and zlw with scalar values at the mouth, or a
%        vector with the same dimension as the x vector, or CF_HydroData instance
%   histdst - dstable of hypsometry(x,z) matrix generated by gd_basin_hypsometry.
% OUTPUT
%   cprops - table of cumulative (from head) along-channel/x-axis properties,
%            inludes surface areas, S, volumes, V, tidal prism, Pr, 
%            Dronkers gamma,storage volume Vs, Channel volume,Vc, 
%            hydraulic depth, hyd, and tidal, amplidue, amp:
%            Shw,Smt,Slw,Vhw,Vmt,Vlw,PrV,Gamma,Vs,Vc,hyd,amp
%   xprops - table of incremental properties for each x-interval, inludes:
%            Shwx,Smtx,Slwx,Vhwx,Vmtx,Vlwx,Prvx
% NOTES
%   this function is only valid for cartesian grids of constant grid size.
%   takes account of along-channel variations in water level when computing
%   gross properties (e.g. volumes and tidal prism).
% SEE ALSO
%   gd_basin_hypsometry which outputs area and volume for whole channel
%   and is used in GDinterface, along with gd_gross_properties and
%   this function is called in gd_section_properties. 
%
% Author: Ian Townend
% CoastalSEA (c) July 2022
%--------------------------------------------------------------------------
%
    nx = length(grid.x);
    
    ich = gd_basin_indices(grid); %account for offset to mouth and head (if defined)
    if isscalar(wl.zhw)           %ensure that water levels are a vector
        zhw = ones(1,nx)*wl.zhw;
        zmt = ones(1,nx)*wl.zmt;
        zlw = ones(1,nx)*wl.zlw;
    else 
        zhw = wl.zhw;
        zmt = wl.zmt;
        zlw = wl.zlw;    
    end
    histint = histdst.UserData.histint; 
    
    %hdst = gd_basin_hypsometry(grid,wl,histint,limits,isHW);
    zhist = squeeze(histdst.SArea);
    zcentre = histdst.Dimensions.Z;
    %cumulative surface area at or below each elevation z for each x inteval
    %such that hyps.zsurf = sum(hyps.xzsurf,1);
    xzsurf = cumsum(zhist,2);
    %cumulative volume at or below each elevation z for each x interval
    %such that hyps.zvol = sum(hyps.xzvol,1);
    xzvol = cumtrapz(histint,xzsurf,2);

    %Surface area and volumes at each x interval and each tidal elevation
    Vhwx = zeros(1,nx); Vmtx = Vhwx; Vlwx = Vhwx; 
    Shwx = Vhwx; Smtx = Vhwx; Slwx = Vhwx;

    for ix=ich
        Shwx(1,ix) = interp1(zcentre,xzsurf(ix,:),zhw(ix),'linear','extrap');
        Smtx(1,ix) = interp1(zcentre,xzsurf(ix,:),zmt(ix),'linear','extrap');
        Slwx(1,ix) = interp1(zcentre,xzsurf(ix,:),zlw(ix),'linear','extrap');
        Vhwx(1,ix) = interp1(zcentre,xzvol(ix,:),zhw(ix),'linear','extrap');
        Vmtx(1,ix) = interp1(zcentre,xzvol(ix,:),zmt(ix),'linear','extrap');
        Vlwx(1,ix) = interp1(zcentre,xzvol(ix,:),zlw(ix),'linear','extrap');        
    end  
    Prvx = Vhwx-Vlwx;    %prism within each x-interval
    amp = (zhw-zlw)/2;   %along-channel tidal amplitude
    if iscolumn(amp), amp = amp'; end
    ChPx = amp.*Slwx;    %half-prism over channel (lw) in each reach
    
    %cumulative along-channel area and volume for each tidal elevation
    Vhw = zeros(1,nx); Vmt = Vhw; Vlw = Vhw; Shw = Vhw; Smt = Vhw; Slw = Vhw; ChP = Vhw;
    gdax = gd_ax_dir(grid,grid.x); %check direction axis relative to head/mouth
    for ix=ich
        if gdax.x==1 || gdax.x==4 %x-ascending and ishead, or
            indices = 1:ix;       %x-descending and ~ishead
        else                      %x-ascending and ~ishead, or
            indices = ix:nx;      %x-descending and ishead
        end
        Shw(1,ix) = sum(Shwx(indices));
        Smt(1,ix) = sum(Smtx(indices));
        Slw(1,ix) = sum(Slwx(indices));
        Vhw(1,ix) = sum(Vhwx(indices));
        Vmt(1,ix) = sum(Vmtx(indices));
        Vlw(1,ix) = sum(Vlwx(indices));
        ChP(1,ix) = sum(ChPx(indices)); %cumulative half-prism over channel
    end
    PrV = Vhw-Vlw;
    
    beta = 1;              %assume Schw/Sclw = 1 
    Gamma = ((Slw./Shw).^3.*(Vhw./Vlw).^2)*beta; %Dronkers gamma (~1)
    Vs  = (Vhw-Vlw)-2*ChP; %storage volume over intertidal
    Vc  = Vlw+ChP;         %channel volume = low water volume+half-prism over channel
    hyd = Vmt./Smt;        %hydraulic depth at mtl    
    %table of areas and volumes for each x-interval
    xprops = table(Shwx,Smtx,Slwx,Vhwx,Vmtx,Vlwx,Prvx);    
    %table of summary properties as cumulative values from head
    cprops = table(Shw,Smt,Slw,Vhw,Vmt,Vlw,PrV,Gamma,Vs,Vc,hyd,amp);  
end
    