function SFC = SFcodes
%-------script help------------------------------------------------------
% NAME
%   SFcodes.m
% PURPOSE
%   Standard Feature Codes (FC) for Topographic Surveys
% USAGE
%   SFC = SFcodes;
% OUTPUT
%   SFC- struct containting code, code name, code id
% NOTES
%   see Channel Coast Observatory for further details
% SEE ALSO
%   profile_cco_formats.m for usage
%
% Author: Ian Townend
% CoastalSEA (c)June 2015
%----------------------------------------------------------------
SFC = {...
    'ZZ','Unknown',1;...
    'S','Sand',2;...
    'M','Mud',3;...
    'MS','Mud&Sand',4;...
    'G','Gravel',5;...
    'VG','Vegetated gravel',5;...       %non-standard code
    'GS','Gravel&Sand',6;...
    'GM','Gravel&Mud',7;...    
    'X','Mixture',8;...
    'MX','Mixture',8;...                %non-standard code
    'SH','Shell',9;... 
    'BO','Boulders',10;...
    'R','Rock',11;...    
    'SM','Saltmarsh',12;...
    'HW','High water mark',13;...
    'SD','Sea defence',14;...
    'W','Water body',15;...    
    'GR','Grass',16;...
    'D','Dune',17;...
    'DV','Vegetated dune',18;...
    'F','Forested',19;...    
    'FB','Obstruction',20;...
    'CT','Cliff top',21;...
    'CL','Cliff line',21;...           %non-standard code
    'CE','Clif edge',22;...
    'CF','Cliff face',23;...    
    'SP','Start point of line',24;...
    'ZCP','Start point of line',24};  %non-standard code (but in EA spec)
